spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/vin-service'
    username: vin-service
    password: vin-service
    hikari:
      schema: public
      connection-timeout: 2000
      maximum-pool-size: 20
  jpa:
    open-in-view: false
    show-sql: true
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: none
  application:
    name: vin_service
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jackson:
    mapper:
      accept-case-insensitive-enums: true

server:
  port: 8080
  max-http-header-size: 16384

logging:
  level:
    root: WARN
  file:
    name: ./vinservicelogs/vinservice.log

vin-service:
  contact:
    title: Vin Service API
    description: Documentation for VIN Service APIs
    url: https://innocito.com/
    team: Innocito Team
    email:
    license: Apache 2.0 License
    terms: Terms of Service
    version: 1.0.0
  memoryCache:
    name: vin_service_memory_cache
    permitNullValues: false

rivian:
  url: https://rivian.com/api/gql/gateway/graphql
  email: test@gmail.com
  password: test1234

brand:
  rivian:
    url: https://rivian.com/api/gql/gateway/graphql
    email: test@gmail.com
    password: test1234
    secretKey: testSecret
    vasPhoneId: test1234
    deviceId: test1234
  tesla:
    url: https://fleet-auth.prd.vn.cloud.tesla.com
    clientId: test1234
    clientSecret: test1234
    grantType: client_credentials
    scope: openid user_data vehicle_device_data vehicle_location vehicle_cmds vehicle_charging_cmds
    audience: test1234