package com.innocito.tesla;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AccessLevel;
import lombok.RequiredArgsConstructor;

@RequiredArgsConstructor(access = AccessLevel.PUBLIC)
public enum TeslaVehicleCommand {
  ACTUATE_TRUNK,
  ADD_CHARGE_SCHEDULE,
  ADD_PRECONDITION_SCHEDULE,
  ADJUST_VOLUME,
  AUTO_CONDITIONING_START,
  AUTO_CONDITIONING_STOP,
  CANCEL_SOFTWARE_UPDATE,
  CHARGE_MAX_RANGE,
  CHARGE_PORT_DOOR_CLOSE,
  CHARGE_PORT_DOOR_OPEN,
  CHARGE_STANDARD,
  CHARGE_START,
  CHARGE_STOP,
  CLEAR_PIN_TO_DRIVE_ADMIN,
  DOOR_LOCK,
  DOOR_UNLOCK,
  ERASE_USER_DATA,
  FLASH_LIGHTS,
  GUEST_MODE,
  HONK_HORN,
  MEDIA_NEXT_FAV,
  MEDIA_NEXT_TRACK,
  MEDIA_PREV_FAV,
  MEDIA_PREV_TRACK,
  MEDIA_TOGGLE_PLAYBACK,
  MEDIA_VOLUME_DOWN,
  NAVIGATION_GPS_REQUEST,
  NAVIGATION_REQUEST,
  NAVIGATION_SC_REQUEST,
  NAVIGATION_WAYPOINTS_REQUEST,
  REMOTE_AUTO_SEAT_CLIMATE_REQUEST,
  REMOTE_AUTO_STEERING_WHEEL_HEAT_CLIMATE_REQUEST,
  REMOTE_BOOMBOX,
  REMOTE_SEAT_COOLER_REQUEST,
  REMOTE_SEAT_HEATER_REQUEST,
  REMOTE_START_DRIVE,
  REMOTE_STEERING_WHEEL_HEAT_LEVEL_REQUEST,
  REMOTE_STEERING_WHEEL_HEATER_REQUEST,
  REMOVE_CHARGE_SCHEDULE,
  REMOVE_PRECONDITION_SCHEDULE,
  RESET_PIN_TO_DRIVE_PIN,
  RESET_VALET_PIN,
  SCHEDULE_SOFTWARE_UPDATE,
  SET_BIOWEAPON_MODE,
  SET_CABIN_OVERHEAT_PROTECTION,
  SET_CHARGE_LIMIT,
  SET_CHARGING_AMPS,
  SET_CLIMATE_KEEPER_MODE,
  SET_COP_TEMP,
  SET_PIN_TO_DRIVE,
  SET_PRECONDITIONING_MAX,
  SET_SCHEDULED_CHARGING,
  SET_SCHEDULED_DEPARTURE,
  SET_SENTRY_MODE,
  SET_TEMPS,
  SET_VALET_MODE,
  SET_VEHICLE_NAME,
  SPEED_LIMIT_ACTIVATE,
  SPEED_LIMIT_CLEAR_PIN,
  SPEED_LIMIT_CLEAR_PIN_ADMIN,
  SPEED_LIMIT_DEACTIVATE,
  SPEED_LIMIT_SET_LIMIT,
  SUN_ROOF_CONTROL,
  TRIGGER_HOMELINK,
  UPCOMING_CALENDAR_ENTRIES,
  WINDOW_CONTROL;

  @JsonCreator
  public static TeslaVehicleCommand fromValue(String value) {
    return TeslaVehicleCommand.valueOf(value.toUpperCase());
  }

  @JsonValue
  public String toValue() {
    return this.name();
  }
}
